import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LOVE ON TOUR',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className='flex justify-center p-14'>
        <ul className='flex text-lg gap-8'>
          <li>
            <Link href="/">HOME</Link>
          </li>
          <li>
            <Link href="/about-hs">ABOUT HS</Link>
          </li>
          <li>
            <Link href="/lot">LOT</Link>
          </li>
          <li>
            <Link href="/style">STYLE</Link>
          </li>
          <li>
            <Link href="/bts">BTS</Link>
          </li>
          <li>
            <Link href="/fans">FANS</Link>
          </li>
        </ul>
      </nav>
        {children}</body>
    </html>
  )
}
