import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { FC, useState } from "react";
import Image from "next/image";


const pages = {
  home: "/",
  bts: "/bts",
  fans: "/fans",
  lot: "/lot",
  style:"/style"
};

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LOVE ON TOUR',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body className={inter.className}>  
      <nav className='navbar'>
      <Image
          className="nav-logo"
          src="/hslogo.svg"
          width={93}
          height={65}
          alt="Navbar logo"
        />
        <ul className="navbar-elements">
        {Object.entries(pages).map(([name, path]) => (
              <li key={name}>
                <Link href={path}>{name.toUpperCase()}</Link>
              </li>
            ))}
          <li>
            <Link href="/about-hs">ABOUT HS</Link>
            </li>
        
        </ul>
      </nav>
        {children}</body>
    </html>
  )
}
